services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=moodle
      - POSTGRES_USER=moodle
      - POSTGRES_PASSWORD=password
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  web:
    image: ghcr.io/emneo-dev/moodle:latest
    build: .
    ports:
      - 8080:80
    security_opt:
      - label=disable
    links:
      - db
    volumes:
      - ./.data/web:/moodledata:rw
    environment:
      - MOODLE_DB_TYPE=pgsql
      - MOODLE_DB_HOST=db
      - MOODLE_DB_PORT=5432
      - MOODLE_DB_NAME=moodle
      - MOODLE_DB_USER=moodle
      - MOODLE_DB_PASSWORD=password
      - MOODLE_DB_PREFIX=
      - MOODLE_URL=http://localhost:8080
      #- MOODLE_SITE_FULLNAME=
      #- MOODLE_SITE_SHORTNAME=
      - MOODLE_SITE_LANG=fr
      #- MOODLE_ADMIN_USER=
      #- MOODLE_ADMIN_PASS=
      #- MOODLE_ADMIN_EMAIL=
      #- MOODLE_UPDATE=
      - MOODLE_REVERSE_PROXY=true
      #- MOODLE_SSL_PROXY=false
      - MOODLE_REDIS_HOST=redis
      - MOODLE_REDIS_PORT=6379
      - MOODLE_REDIS_DB=0
      #- MOODLE_REDIS_PREFIX=''
      - MOODLE_DISABLE_UPDATE_AUTODEPLOY=true
      #- MOODLE_DEBUG=true
      #- SMTP_HOST=example.com:465
      #- SMTP_USER=test
      #- SMTP_PASS=testpass
      #- SMTP_SECURITY=ssl
      #- SMTP_AUTH_TYPE=PLAIN
      #- MOODLE_NOREPLY_ADDRESS=test@example.com
  redis:
    image: redis:6-alpine
    volumes:
      - ./.data/redis:/data
    ports:
      - 6379:6379
