# Taken from: https://github.com/TrafeX/docker-php-nginx/blob/36727ce67a98c340a8cadbd2aaf9c9f129dde04c/config/php.ini

upload_max_filesize=${UPLOAD_MAX_FILESIZE}
post_max_size=${UPLOAD_MAX_FILESIZE}
memory_limit=${PHP_MEMORY_LIMIT}
max_execution_time=${PHP_MAX_EXECUTION_TIME}
max_input_vars=${PHP_MAX_INPUT_VARS}

[Date]
date.timezone="UTC"
expose_php= Off