name: Build image(s)

on:
  push:

env:
  IMAGE_TAG: ghcr.io/emneo-dev/moodle

permissions:
  packages: write
  contents: read

jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v6
      - uses: docker/metadata-action@v5
        id: image-metadata
        with: 
          images: ${{ env.IMAGE_TAG }}
          tags: |
            type=raw,value=amd64
      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v7
        with:
          push: true
          platforms: linux/amd64
          tags: ${{ steps.image-metadata.outputs.tags }}

  merge:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps: 
      - uses: actions/checkout@v6
      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          docker buildx imagetools create \
            --tag ${{ env.IMAGE_TAG }}:latest ${{ env.IMAGE_TAG }}:amd64